spring.application.name=backend
server.port=8081
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/paf
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Optional (recommended)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# OAuth Google
spring.security.oauth2.client.registration.google.client-id=158370530762-e671k3g7b2qeutfjh4gq15ej2h74vjo5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
